#!/bin/bash

# Star Wars ASCII art
starwars_art="
                                   _________
                                 /         /.
   .-------------.           /         //.
  /             / |         /         // |
 /+============+\ |       /         //  |
 ||            || |      /_________//   |
 ||            || |      |   _ _  |     |
 ||            || |      |  |   | |     |
 ||            ||/@@    |  |   |_|     |
 ||            ||       |  |    _      |
 ||            ||       |  |   | |     |
 ||            ||       |  |   | |     |
 ||            ||       |  |   |_|     |
 ||            ||       |  |           |
 ||            ||       |  |           |
 ||            ||       |  |           |
 ||            ||      /+ _|_+\\       |
 ||            ||     /_________\\      |
 ||            ||    |           |     |
 ||            ||    |           |     |
 ||   .========++====+|   _____   |     |
 ||  /         /./.   ||  ||   ||  |     |
 || /         / / /   ||  ||   ||  |     |
 ||/_________/_/ /____|  ||___||  |_____|
 |              | /         ||   ||       /
 |______________|/          ||___||      /
                                |      /
                                |_____/
"

# Function to display the Star Wars ASCII art
play_starwars() {
    echo "$starwars_art"
    sleep 3
    clear
}

# Play Star Wars
play_starwars

# Connect to the Star Wars Episode IV server
telnet towel.blinkenlights.nl

